[package]
name = "raytracer"
version = "0.1.0"
authors = ["jeremyt135 <jdt13579@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.3"
rand = "0.7.3"
rayon = "1.5.0"
indicatif = "0.15.0"
clap = "2.33.3"
image = "0.23.11"